services:
  - type: web
    name: nigerian-university-list-api
    env: go
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: GOTOOLCHAIN
        value: go1.24.6